### PR TITLE
m_osx_addressbook: add company and nickname search

### PR DESCRIPTION
**Pull request by seebi**
- this addition allows for matching input string also with
  company name and nickname
- thanks to @pfrischmuth for the help

### CODE REVIEW

**Comment by tgray** [comment]
Thanks for this.  Nice work.  It cleaned up some other bit of brokenness that the intervening months of OS X had introduced too.

I will probably snag some of this code for the lbdb replacement I'm working on.

**Comment by seebi** [comment]
Hi Tim, where is this replacement?

**Comment by tgray** [comment]
Working on polishing it up.  :)

**Comment by seebi** [comment]
:) so keep me updated please ..

**Pull request merged**
